project:
  type: manuscript

execute:
  freeze: false
  echo: true
  eval: true
  output: true

format:
  html:
    toc: true
    number-sections: true 
    toc-depth: 3
    comments:
      hypothesis: true
  docx: default
  jats: default
  agu-pdf: default



